### ISSUE TITLE
Error after `npm run dist:mac`: Not allowed to load local resource

### ISSUE THREAD

**Issue by johnlindquist** [egoist/template-electron#4]
```
Not allowed to load local resource: file:///Users/johnlindquist/projects/build-test/dist/mac/Build-test.app/Contents/Resources/app.asar/renderer/index.html
```

Steps to reproduce:
1. sao electron build-test
2. Make sure to select "Y" for webpack option
3. Run `npm run dist:mac`
4. Launch build-test app

**Comment by egoist** [comment]
hmm yeah you should run `npm run build` first to bundle renderer to `app/renderer`, we should add some docs 😅

**Comment by johnlindquist** [comment]
Oh, whoopsie. I'll add some docs tomorrow :) thanks

**Comment by egoist** [comment]
haha I do run into this issue sometimes too 😅

**Comment by egoist** [comment]
Forgot that there's already some doc for this: https://github.com/egoist/template-electron/blob/master/docs/webpack.md

And I just updated the npm scripts a little bit 😄  now the script names make more sense
